#!/usr/bin/env node

let { writeFile, readFile, copyFile, unlink } = require('fs').promises
let { basename, join } = require('path')
let postcssUrl = require('postcss-url')
let posthtml = require('posthtml')
let makeDir = require('make-dir')
let Bundler = require('parcel-bundler')
let postcss = require('postcss')
let crypto = require('crypto')

const SRC = join(__dirname, '..', 'src')
const DIST = join(__dirname, '..', 'dist')

async function compileAssets () {
  let uikitBundler = new Bundler(join(SRC, 'uikit.pug'), {
    sourceMaps: false
  })
  let bundle = await uikitBundler.bundle()

  function findAssets (step) {
    return Array.from(step.childBundles).reduce((all, i) => {
      return all.concat(findAssets(i))
    }, [step.name])
  }
  let assets = findAssets(bundle)
  return function getAssets (regexp) {
    return assets.filter(i => regexp.test(i))
  }
}

async function copyWellKnown () {
  let wellFrom = join(SRC, 'well-known')
  let wellTo = join(DIST, '.well-known')
  let files = ['favicon.ico', 'robots.txt']
  await makeDir(join(DIST, '.well-known'))
  await Promise.all(files
    .map(i => copyFile(join(wellFrom, i), join(DIST, i)))
    .concat([
      join(wellFrom, 'security.txt.asc'), join(wellTo, 'security.txt')
    ]))
}

async function generateWebManifest (getAssets) {
  let json = JSON.parse(
    await readFile(join(SRC, 'base', 'manifest.webmanifest'))
  )
  json.icons[0].src = '/' + basename(getAssets(/196\..*\.png$/)[0])
  json.icons[1].src = '/' + basename(getAssets(/512\..*\.png$/)[0])
  let text = JSON.stringify(json)
  let hash = crypto.createHash('md5').update(text).digest('hex').slice(0, 8)
  let name = `manifest.${ hash }.webmanifest`
  await writeFile(join(DIST, name), text)
  return { url: '/' + name, theme: json.theme_color }
}

async function findFilesInCSS (getAssets) {
  let collected = []
  let fileCollector = postcssUrl({
    url ({ url }) {
      collected.push(url)
      return url
    }
  })
  await Promise.all(getAssets(/\.css$/).map(async file => {
    let css = await readFile(file)
    await postcss([fileCollector]).process(css, { from: file })
  }))
  return collected
}

async function updateHtml (manifest, preloadFiles) {
  let [html] = await Promise.all([
    readFile(join(DIST, 'uikit.html')),
    makeDir(join(DIST, 'uikit'))
  ])
  function htmlPlugin (tree) {
    tree.match({ attrs: { rel: 'icon', sizes: '512x512' } }, () => {
      return [
        { tag: 'link', attrs: { rel: 'manifest', href: manifest.url } },
        { tag: 'meta', attrs: { name: 'theme-color', content: manifest.theme } }
      ].concat(preloadFiles.map(href => ({
        tag: 'link', attrs: { rel: 'preload', href, as: 'font' }
      })))
    })
  }
  let fixed = posthtml().use(htmlPlugin).process(html, { sync: true }).html
  await Promise.all([
    writeFile(join(DIST, 'uikit', 'index.html'), fixed),
    unlink(join(DIST, 'uikit.html'))
  ])
}

async function build () {
  let [getAssets] = await Promise.all([
    compileAssets(),
    copyWellKnown()
  ])
  let [webmanifest, filesFromCSS] = await Promise.all([
    generateWebManifest(getAssets),
    findFilesInCSS(getAssets)
  ])
  await updateHtml(webmanifest, filesFromCSS)
}

build().catch(e => {
  process.stderr.write(e.stack + '\n')
  process.exit(1)
})
