#!/bin/bash

IMAGE=gcr.io/logux-255417/loguxio

main () {
  local DELETED=0
  for digest in $(
    gcloud container images list-tags $IMAGE \
      --filter='-tags:*' --format='get(digest)'
  ); do
    gcloud container images delete "${IMAGE}@${digest}"
    let DELETED=DELETED+1
  done
  echo "Deleted ${DELETED} images in ${IMAGE}"
}

main
